services:

  api:

    build:
      context: .
      dockerfile: Dockerfile

    container_name: ai-bi-api

    restart: unless-stopped

    env_file:
      - .env.docker

    ports:
      - "8000:8000"

    volumes:
      - .:/app
      - storage_data:/app/storage

volumes:

  storage_data:
